# netlify.toml

[build]
    command = "npm run build && npm run export"
    publish = "out"

[context.production]
  environment = { NODE_ENV = "production" }

[context.test]
  environment = { NODE_ENV = "test" }

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
