# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"

#[context.production]
#  environment = { NODE_ENV = "production" }

#[context.test]
#  environment = { NODE_ENV = "test" }

[context.production.environment]
  NEXT_PUBLIC_API_ENV = "production"

[context.staging.environment]
  NEXT_PUBLIC_API_ENV = "staging"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"