# netlify.toml

[build]
  command = "npm run build"
  publish = ".next"


[context.production]
  environment = { NODE_ENV = "production" }

[context.staging]
  environment = { NODE_ENV = "staging" }

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/*"
to = "/not-found"
status = 404
